/** Bundled Core Competencies catalog — shipped in the extension (core-competencies-seed.ts). */

export interface SeedCompetency {
  title: string;
  category: string;
}

export const SEED_CORE_COMPETENCIES: SeedCompetency[] = [
  // Leadership & Management
  { title: 'Leadership', category: 'Leadership & Management' },
  { title: 'Engineering Leadership', category: 'Leadership & Management' },
  { title: 'Technical Leadership', category: 'Leadership & Management' },
  { title: 'People Management', category: 'Leadership & Management' },
  { title: 'Team Building', category: 'Leadership & Management' },
  { title: 'Talent Development', category: 'Leadership & Management' },
  { title: 'Coaching and Mentoring', category: 'Leadership & Management' },
  { title: 'Organizational Design', category: 'Leadership & Management' },
  { title: 'Stakeholder Management', category: 'Leadership & Management' },
  { title: 'Executive Communication', category: 'Leadership & Management' },
  { title: 'Decision Making', category: 'Leadership & Management' },
  { title: 'Conflict Resolution', category: 'Leadership & Management' },
  { title: 'Influence Without Authority', category: 'Leadership & Management' },
  { title: 'Remote Team Leadership', category: 'Leadership & Management' },
  { title: 'Matrix Organization Leadership', category: 'Leadership & Management' },
  { title: 'Hybrid Workforce Management', category: 'Leadership & Management' },
  { title: 'Board and Investor Relations', category: 'Leadership & Management' },
  { title: 'Public Speaking', category: 'Leadership & Management' },
  { title: 'Negotiation', category: 'Leadership & Management' },

  // Strategy & Business
  { title: 'Strategic Planning', category: 'Strategy & Business' },
  { title: 'Technology Strategy', category: 'Strategy & Business' },
  { title: 'Technical Vision', category: 'Strategy & Business' },
  { title: 'Technology Roadmapping', category: 'Strategy & Business' },
  { title: 'Change Management', category: 'Strategy & Business' },
  { title: 'Innovation Management', category: 'Strategy & Business' },
  { title: 'Business Strategy', category: 'Strategy & Business' },
  { title: 'Digital Transformation', category: 'Strategy & Business' },
  { title: 'Operational Excellence', category: 'Strategy & Business' },
  { title: 'Customer Experience', category: 'Strategy & Business' },
  { title: 'Business Process Improvement', category: 'Strategy & Business' },
  { title: 'Revenue Growth', category: 'Strategy & Business' },
  { title: 'Go-to-Market Strategy', category: 'Strategy & Business' },
  { title: 'P&L Ownership', category: 'Strategy & Business' },
  { title: 'Vendor Management', category: 'Strategy & Business' },
  { title: 'Budget Management', category: 'Strategy & Business' },
  { title: 'Technical Due Diligence', category: 'Strategy & Business' },
  { title: 'Mergers and Acquisitions Integration', category: 'Strategy & Business' },
  { title: 'OKRs', category: 'Strategy & Business' },
  { title: 'Workforce Planning', category: 'Strategy & Business' },
  { title: 'Succession Planning', category: 'Strategy & Business' },

  // Product
  { title: 'Product Strategy', category: 'Product' },
  { title: 'Product Development', category: 'Product' },
  { title: 'Product Delivery', category: 'Product' },
  { title: 'Product Lifecycle Management', category: 'Product' },
  { title: 'Product Led Growth', category: 'Product' },
  { title: 'User Research', category: 'Product' },
  { title: 'UX Strategy', category: 'Product' },

  // Software Engineering
  { title: 'Software Development', category: 'Software Engineering' },
  { title: 'Full Stack Development', category: 'Software Engineering' },
  { title: 'Backend Development', category: 'Software Engineering' },
  { title: 'Frontend Development', category: 'Software Engineering' },
  { title: 'Mobile Development', category: 'Software Engineering' },
  { title: 'Platform Engineering', category: 'Software Engineering' },
  { title: 'Cloud Engineering', category: 'Software Engineering' },
  { title: 'API Design', category: 'Software Engineering' },
  { title: 'API Management', category: 'Software Engineering' },
  { title: 'REST API Development', category: 'Software Engineering' },
  { title: 'GraphQL', category: 'Software Engineering' },
  { title: 'Microservices', category: 'Software Engineering' },
  { title: 'Distributed Systems', category: 'Software Engineering' },
  { title: 'Event Driven Architecture', category: 'Software Engineering' },
  { title: 'System Design', category: 'Software Engineering' },
  { title: 'Database Design', category: 'Software Engineering' },
  { title: 'Technical Debt Management', category: 'Software Engineering' },
  { title: 'Software Development Lifecycle', category: 'Software Engineering' },
  { title: 'Engineering Excellence', category: 'Software Engineering' },
  { title: 'Developer Productivity', category: 'Software Engineering' },
  { title: 'Quality Engineering', category: 'Software Engineering' },
  { title: 'Test Automation', category: 'Software Engineering' },
  { title: 'Technical Writing', category: 'Software Engineering' },
  { title: 'Open Source Strategy', category: 'Software Engineering' },

  // Architecture
  { title: 'Application Architecture', category: 'Architecture' },
  { title: 'Enterprise Architecture', category: 'Architecture' },
  { title: 'Solution Architecture', category: 'Architecture' },
  { title: 'Scalability Engineering', category: 'Architecture' },
  { title: 'Performance Optimization', category: 'Architecture' },
  { title: 'Reliability Engineering', category: 'Architecture' },
  { title: 'Web Performance', category: 'Architecture' },
  { title: 'Accessibility', category: 'Architecture' },

  // Cloud & Infrastructure
  { title: 'Cloud Architecture', category: 'Cloud & Infrastructure' },
  { title: 'Cloud Migration', category: 'Cloud & Infrastructure' },
  { title: 'Multi-Cloud Strategy', category: 'Cloud & Infrastructure' },
  { title: 'AWS', category: 'Cloud & Infrastructure' },
  { title: 'Azure', category: 'Cloud & Infrastructure' },
  { title: 'Google Cloud Platform', category: 'Cloud & Infrastructure' },
  { title: 'Kubernetes', category: 'Cloud & Infrastructure' },
  { title: 'Containerization', category: 'Cloud & Infrastructure' },
  { title: 'Infrastructure as Code', category: 'Cloud & Infrastructure' },
  { title: 'Terraform', category: 'Cloud & Infrastructure' },
  { title: 'Site Reliability Engineering', category: 'Cloud & Infrastructure' },
  { title: 'Infrastructure Automation', category: 'Cloud & Infrastructure' },
  { title: 'Observability', category: 'Cloud & Infrastructure' },
  { title: 'Monitoring and Alerting', category: 'Cloud & Infrastructure' },
  { title: 'Disaster Recovery', category: 'Cloud & Infrastructure' },
  { title: 'Serverless Computing', category: 'Cloud & Infrastructure' },
  { title: 'FinOps', category: 'Cloud & Infrastructure' },
  { title: 'Cost Optimization', category: 'Cloud & Infrastructure' },
  { title: 'Capacity Planning', category: 'Cloud & Infrastructure' },
  { title: 'Chaos Engineering', category: 'Cloud & Infrastructure' },
  { title: 'Incident Management', category: 'Cloud & Infrastructure' },
  { title: 'Edge Computing', category: 'Cloud & Infrastructure' },

  // AI & Data
  { title: 'Artificial Intelligence', category: 'AI & Data' },
  { title: 'Generative AI', category: 'AI & Data' },
  { title: 'Agentic AI', category: 'AI & Data' },
  { title: 'Machine Learning', category: 'AI & Data' },
  { title: 'Deep Learning', category: 'AI & Data' },
  { title: 'Natural Language Processing', category: 'AI & Data' },
  { title: 'Computer Vision', category: 'AI & Data' },
  { title: 'AI Strategy', category: 'AI & Data' },
  { title: 'LLM Integration', category: 'AI & Data' },
  { title: 'Prompt Engineering', category: 'AI & Data' },
  { title: 'Retrieval Augmented Generation', category: 'AI & Data' },
  { title: 'Vector Databases', category: 'AI & Data' },
  { title: 'MLOps', category: 'AI & Data' },
  { title: 'LLMOps', category: 'AI & Data' },
  { title: 'Feature Engineering', category: 'AI & Data' },
  { title: 'Model Deployment', category: 'AI & Data' },
  { title: 'Responsible AI', category: 'AI & Data' },
  { title: 'AI Ethics', category: 'AI & Data' },
  { title: 'Automation Strategy', category: 'AI & Data' },
  { title: 'Data Engineering', category: 'AI & Data' },
  { title: 'Data Analytics', category: 'AI & Data' },
  { title: 'Data Platforms', category: 'AI & Data' },
  { title: 'Business Intelligence', category: 'AI & Data' },
  { title: 'Data Governance', category: 'AI & Data' },
  { title: 'ETL Pipelines', category: 'AI & Data' },
  { title: 'People Analytics', category: 'AI & Data' },
  { title: 'Experimentation Platforms', category: 'AI & Data' },

  // Security & Compliance
  { title: 'Cybersecurity', category: 'Security & Compliance' },
  { title: 'DevSecOps', category: 'Security & Compliance' },
  { title: 'Application Security', category: 'Security & Compliance' },
  { title: 'Zero Trust Security', category: 'Security & Compliance' },
  { title: 'Identity and Access Management', category: 'Security & Compliance' },
  { title: 'Risk Management', category: 'Security & Compliance' },
  { title: 'Risk Mitigation', category: 'Security & Compliance' },
  { title: 'Governance', category: 'Security & Compliance' },
  { title: 'Compliance Management', category: 'Security & Compliance' },
  { title: 'Data Privacy', category: 'Security & Compliance' },

  // Delivery & Operations
  { title: 'Agile Methodologies', category: 'Delivery & Operations' },
  { title: 'Scrum', category: 'Delivery & Operations' },
  { title: 'Kanban', category: 'Delivery & Operations' },
  { title: 'SAFe', category: 'Delivery & Operations' },
  { title: 'Lean Delivery', category: 'Delivery & Operations' },
  { title: 'Project Management', category: 'Delivery & Operations' },
  { title: 'Program Management', category: 'Delivery & Operations' },
  { title: 'Portfolio Management', category: 'Delivery & Operations' },
  { title: 'Technical Program Management', category: 'Delivery & Operations' },
  { title: 'Release Management', category: 'Delivery & Operations' },
  { title: 'Continuous Improvement', category: 'Delivery & Operations' },
  { title: 'CI/CD', category: 'Delivery & Operations' },
  { title: 'DevOps', category: 'Delivery & Operations' },
  { title: 'GitOps', category: 'Delivery & Operations' },
  { title: 'Modernization', category: 'Delivery & Operations' },
  { title: 'Platform Modernization', category: 'Delivery & Operations' },

  // Mobile
  { title: 'iOS Development', category: 'Mobile' },
  { title: 'Android Development', category: 'Mobile' },
  { title: 'Cross Platform Development', category: 'Mobile' },
  { title: 'Mobile Architecture', category: 'Mobile' },
  { title: 'Mobile Performance Optimization', category: 'Mobile' },
  { title: 'Mobile Security', category: 'Mobile' },
  { title: 'Mobile User Experience', category: 'Mobile' },

  // Industry Domains
  { title: 'E-Commerce', category: 'Industry Domains' },
  { title: 'Retail Technology', category: 'Industry Domains' },
  { title: 'Healthcare Technology', category: 'Industry Domains' },
  { title: 'Financial Technology', category: 'Industry Domains' },
  { title: 'Telecommunications', category: 'Industry Domains' },
  { title: 'Enterprise SaaS', category: 'Industry Domains' },
  { title: 'Payments', category: 'Industry Domains' },
  { title: 'Digital Commerce', category: 'Industry Domains' },
  { title: 'Supply Chain Technology', category: 'Industry Domains' },

  // People & Culture (ATS additions from HR taxonomy research)
  { title: 'Talent Acquisition', category: 'People & Culture' },
  { title: 'Employee Engagement', category: 'People & Culture' },
  { title: 'Learning and Development', category: 'People & Culture' },
  { title: 'Diversity Equity and Inclusion', category: 'People & Culture' },
  { title: 'Performance Management', category: 'People & Culture' },
  { title: 'Organizational Development', category: 'People & Culture' },

  // Collaboration
  { title: 'Customer Centricity', category: 'Collaboration' },
  { title: 'Cross Functional Collaboration', category: 'Collaboration' },
  { title: 'Strategic Partnerships', category: 'Collaboration' },
  { title: 'Thought Leadership', category: 'Collaboration' },
];
